name = "S2Geography"
uuid = "1ece8e93-3e15-4f65-8d0f-0986d38d672b"
authors = ["Anshul Singhvi <anshulsinghvi@gmail.com>"]
version = "0.1.0"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"

[compat]
CEnum = "0.5"
GeoInterface = "1.6"
julia = "1.11"
