"""
    S2Geography.CAPI

Raw, unsafe bindings to the `s2geography_c` shared library.

The contents of this module are generated by `gen/generator.jl` from
`s2geography_c.h` and mirror the C API one-to-one. Everything here is
`unsafe`: pointers are unmanaged, preconditions are unchecked, and error
codes are returned rather than thrown. Prefer the high-level `S2Geography` API
unless you need something it does not expose.
"""
module CAPI

using S2Geography_jll: libs2geography_c

include("generated/libs2geography_c_api.jl")

end # module CAPI
